import assert from 'node:assert/strict';
import { mkdirSync,writeFileSync,readFileSync } from 'node:fs';
import { resolve,join } from 'node:path';
import { unzipSync } from 'fflate';
import { bundleBrowser } from './lib/bundle-browser.mjs';
import { recordCount } from './lib/measured.mjs';
const root=resolve('.'),out=join(root,'out/three-d');mkdirSync(out,{recursive:true});
const entry=join(out,'entry.mjs');writeFileSync(entry,`export * as core from '${root}/packages/core/src/index.ts';export * as spatial from '${root}/packages/core/src/three-d.ts';export * as path from '${root}/packages/core/src/three-d/path.ts';export * as edit from '${root}/packages/edit-core/src/index.ts';export * as appearance from '${root}/packages/edit-core/src/appearance/index.ts';`);
const bundled=await bundleBrowser({root,entry,output:join(out,'contract.mjs'),aliases:[['@web-ppt/core/geometry',join(root,'packages/core/src/geometry/index.ts')],['@web-ppt/core',join(root,'packages/core/src/index.ts')],['@web-ppt/edit-core',join(root,'packages/edit-core/src/index.ts')]]});
const {core,spatial,edit,appearance}=process.argv.includes('--dist') ? {core:await import('@web-ppt/core'),spatial:await import('@web-ppt/core/three-d'),edit:await import('@web-ppt/edit-core'),appearance:await import('@web-ppt/edit-core/appearance')} : bundled;
const {path}=bundled;
let count=0;const check=(c,label)=>{assert(c,label);count++;};const near=(a,b)=>Math.abs(a-b)<1e-6;
const camera=spatial.createCamera(100,100,{rotY:60});const right=camera.project(100,50,0);check(near(right.x,75),'绕 Y 旋转导致真实正面缩短');check(near(right.z,43.3012701892),'深度来自三维旋转');
const roll=spatial.createCamera(100,100,{rotZ:90}).project(100,50,0);check(near(roll.x,50)&&near(roll.y,0),'Z 轴旋转');
const perspective=spatial.createCamera(100,100,{camera:'perspectiveFront',fieldOfView:60});
check(perspective.project(100,50,20).x>perspective.project(100,50,0).x,'透视近大远小');
const zeros=spatial.createCamera(100,100,{rotX:0,rotY:0,rotZ:0}).project(20,30,0);check(near(zeros.x,20)&&near(zeros.y,30),'显式零旋转不注入默认视角');
const paths=path.flattenPath('M0 0h100v100h-100z M20 20v60h60v-60z');check(paths.length===2&&paths.every(p=>p.closed),'轮廓保留反向孔洞');
check(path.flattenPath('M0 0C0 100 100 100 100 0').at(0).points.length>4,'贝塞尔轮廓细分');
check(path.flattenPath('M0 50A50 50 0 1 1 100 50A50 50 0 1 1 0 50Z')[0].points.length>10,'椭圆弧轮廓细分');
check(path.inset(paths[0].points,5)[0].x===5&&path.inset(paths[0].points,5)[0].y===5,'斜角几何偏移');
spatial.enableThreeD();
const source=readFileSync(join(root,'fixtures/sample-three-d.pptx'));
for(const generated of[false,true]){
 const p=await core.parse(source,{edit:true,keepPackage:true,lazy:false}),doc=edit.createDoc(p),editor=new edit.Editor(doc),api=appearance.createAppearanceEditor(editor);
 const shapes=p.slides[0].elements.filter(e=>e.scene3d);check(shapes.length===6,'六种原生三维场景');check(shapes[1].scene3d.rotX===25&&shapes[1].scene3d.rotY===40&&shapes[1].scene3d.rotZ===10,'相机 lat/lon/rev 对应 XYZ');
 check(shapes.every(e=>e.scene3d.extrusion===50),'材质不改变来源挤出深度');
 const svg=core.renderSlideToSvg(p,p.slides[0],{textMode:'svg'});check(svg.includes('data-projection="perspective"')&&svg.includes('data-projection="orthographic"'),'两种投影');check(!/NaN|Infinity/.test(svg),'投影有限');
 check(svg.includes('<text')&&!svg.includes('foreignObject'),'可移植导出保留原生文字');check((svg.match(/fill="rgba\(68,114,196,0.5\)"/g)??[]).length===1,'纯色透视表面只合成一次，不切分填充');writeFileSync(join(out,'source.svg'),svg);
 const id=Object.values(doc.elements).find(r=>r.src.name==='XYZ rotation').id;
 const scene={...appearance.queryScene3D(doc,id),rotX:15,rotY:325,rotZ:22,camera:'perspectiveFront',fieldOfView:60,zoom:1.2,z:10,bevelTop:4,bevelTopWidth:8};
 api.exec({type:'SetScene3D',id,scene});check(editor.effectiveElement(id).scene3d.extrusion===50,'编辑材质深度稳定');editor.undo();check(appearance.queryScene3D(doc,id).rotX===25,'三维编辑撤销');editor.redo();
 if(generated)p.dispose();const saved=await editor.save();writeFileSync(join(out,`${generated?'generated':'patched'}.pptx`),saved);
 const parts=unzipSync(saved),xml=new TextDecoder().decode(parts['ppt/slides/slide1.xml']);check(xml.includes('fov="3600000"')&&xml.includes('zoom="120000"'),'原生相机属性写回');
 const reopened=await core.parse(saved,{edit:true,keepPackage:true,lazy:false}),fresh=new edit.Editor(edit.createDoc(reopened));
 const actual=appearance.queryScene3D(fresh.doc,Object.values(fresh.doc.elements).find(r=>r.src.name==='XYZ rotation').id);
 check(Object.keys(scene).every(k=>typeof scene[k]==='number'?near(scene[k],actual[k]):scene[k]===actual[k]),'两条保存保留三维场景');
 const after=core.renderSlideToSvg(reopened,reopened.slides[0],{textMode:'svg'});check(after.includes('data-depth="50"'),'保存重开不变厚');
 fresh.dispose();reopened.dispose();editor.dispose();p.dispose();
}
recordCount('threeD',count);console.log(`三维投影 ${count} 项通过`);
