import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync,readFileSync } from 'node:fs';
import { resolve,join } from 'node:path';
import { bundleBrowser } from './lib/bundle-browser.mjs';
import { recordCount } from './lib/measured.mjs';
const root=resolve('.'),out=join(root,'out/video');mkdirSync(out,{recursive:true});
const entry=join(out,'entry.mjs');writeFileSync(entry,`export * from '${root}/packages/viewer-core/src/video.ts';export { groupDuration } from '${root}/packages/viewer-core/src/video/timing.ts';export { WebmWriter } from '${root}/packages/viewer-core/src/video/webm.ts';export { parse } from '${root}/packages/core/src/index.ts';`);
const bundled=await bundleBrowser({root,entry,output:join(out,'contract.mjs'),aliases:[['@web-ppt/core',join(root,'packages/core/src/index.ts')]]});
const {videoPlan,presentationToVideo}=process.argv.includes('--dist') ? await import('@web-ppt/viewer-core/video') : bundled;
const {parse}=process.argv.includes('--dist') ? await import('@web-ppt/core') : bundled;
const {groupDuration,WebmWriter}=bundled;
let count=0;const check=(c,label)=>{assert(c,label);count++;};const bad=(fn,re)=>{assert.throws(fn,re);count++;};
const p=await parse(readFileSync('fixtures/sample-video-export.pptx'),{lazy:false});
const plan=videoPlan(p,{fps:12,slideDurationMs:300,clickDelayMs:100,skipHidden:true});
check(plan.pages.length===2,'Hidden slides omitted');check(plan.pages[0].groups[0].length===2,'Native entrance and motion in one click group');
check(groupDuration(plan.pages[0].groups[0])===900,'afterPrev sequencing');check(plan.total>20&&plan.total<40,'Bounded integer frame plan');
check(groupDuration([{delayMs:20,durationMs:40,trigger:'click'},{delayMs:10,durationMs:80,trigger:'withPrev'},{delayMs:5,durationMs:100,trigger:'afterPrev'}])===215,'withPrev and afterPrev relative times');
for(const options of[{fps:0},{fps:61},{fps:NaN},{scale:NaN},{slideDurationMs:-1},{bitrate:Infinity}])bad(()=>videoPlan(p,options),/视频/);
bad(()=>videoPlan({...p,slides:[]},{}),/没有/);bad(()=>videoPlan(p,{slideDurationMs:3600000}),/一小时/);
const writer=new WebmWriter(480,270,12,'VP8');bad(()=>writer.addFrame(new Uint8Array([1]),0,1000,false),/关键帧/);
writer.addFrame(new Uint8Array([1,2,3]),0,83333,true);writer.addFrame(new Uint8Array([4,5]),83333,83334,false);
bad(()=>writer.addFrame(new Uint8Array([6]),83333,83333,false),/递增/);
const webm=writer.finish(),bytes=new Uint8Array(await webm.arrayBuffer());check(webm.type==='video/webm'&&Buffer.from(bytes.subarray(0,4)).toString('hex')==='1a45dfa3','Real EBML signature');
check(Buffer.from(bytes).includes('V_VP8')&&Buffer.from(bytes).includes('webm'),'Native WebM track codec');
bad(()=>writer.finish(),/结束/);bad(()=>new WebmWriter(10,10,24,'VP9').finish(),/没有/);
await assert.rejects(()=>presentationToVideo(p,{signal:AbortSignal.abort()}),e=>e.name==='AbortError');count++;
await assert.rejects(()=>presentationToVideo(p),/WebCodecs/);count++;
p.dispose();recordCount('video',count);console.log(`视频导出 ${count} 项通过`);
